#!/usr/bin/env python

from myoarmpose import MyoArmPose
import sys
import rospy


def main():
	# Elaboro il remapping degli argomenti
	sys.argv = rospy.myargv(sys.argv)
	
	o = MyoArmPose()
	o.run()


if __name__ == '__main__':
	main()
