#!/usr/bin/env python

from rosmyo import RosMyo
import sys
import rospy


def main():
	# Elaboro il remapping degli argomenti
	sys.argv = rospy.myargv(sys.argv)
	
	o = RosMyo()
	o.run()


if __name__ == '__main__':
	main()
